export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const FETCH_ID_USER='FETCH_ID_USER';
export const FETCH_ID_USER_SUCCESS='FETCH_ID_USER_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';


